### ISSUE TITLE
Should Me TV 3 Support Recording?

### ISSUE THREAD

**Issue by dougK44883** [Me-TV/Me-TV#1]
Does your new version ov Me-TV have recording capabilities?  I've been using Me-TV for several  years now and appreciate it's relatively simple UI and setup.  It just does what it's suppose to with out trying to look like like it's something more.

Version 1.3.7-1build2 is necessary for support for the new libs but still uses xine and isn't client/server, with instabilities.  So I have an old computer running debian 8 jessie just to keep the current 1.4.0-0~60~ubuntu14.04.1 working as an OTA dvr.  I haven't found anything worth replacing it.

Irregardless of the capabilities I greatful Me-TV lives on!

**Comment by russel** [comment]
No, at present it is not possible to record using Me TV at the moment. I have been dithering whether to do this.

The question is whether Me TV should be a DVB player or a lightweight DVB PVR. My personal use is as a player, since I have two actual DVB PVRs. Increasingly people are saying DVB is yesterday's technology, it's all now Internet streaming. Clearly I am not in this group or I wouldn't be developing a DVB player!

Then there is the question of what to record. Record from now for a time would be straightforward, especially if I added the ability to play a file – though would that be needed if the recording was in MPEG4 since there is gst-play, gtk-play, and mplayer, all of which can play files. To schedule recording would require either a permanently running server, or connecting with the OS task scheduling system. Also having the EPG to set up a schedule.

Me TV 1.3.7 uses SQLite to cache the EPG, I have not yet got the Rust binding to the MPEG-TS library working, so haven't tackled the EPG problem as yet. This is on the to do list, but is blocked by some issues in the gir_to_rust program – solution is on the way, but as with any project based on volunteers has no deadline.

**Comment by dougK44883** [comment]
I am grateful for your response.  I would add it's all internet streaming
on propitiatory devices or mobile.  HTPC or PCs in general (outside of
business) is indeed yesterday's tech.  Even if it's just perception, I
prefer to have some control, privacy and slight security, what little there
may be with my own (streaming via browser).

Not to suggest to know anything, I understand your response.  Just a point
or two version 1.4.0x won't play it's recordings(?).  It does use a client
/ server model.  1.3 seems to look separate yet you can't shut just the
client down.  Yes, it uses SQlite for storing data, EGP is irreverent.
(well I have it disabled, but it does have a search/record function).  I
know it's not just a few mouse clicks and lines of code.

Again thank you for your time responding, and continuing development with
Me-TV

**Comment by russel** [comment]
I suspect that if the recording facility is to be added, then Me TV should write an H.264/MPEG-4 file to disc. Then it can be played using any H.264/MPEG-4 player (e.g. Glide) and Me TV doesn't have to worry about being a file player, it can just stick to dealing with DVB. True, this means it can't play it's own recordings, but this is about applications doing one thing.

**Comment by dougK44883** [comment]
Yes, the 'old' me-tv didn't play anything other than OTA.  It saved files as ShowName - Channel - FullDate Time_including_seconds.mpeg  Then use smplayer (my choice), vlc or what ever external video player you're happy with.  The scheduling was fairly manual with options for once, daily or weekly.  You'd enter title, pick date and enter time (remembering 8pm is 20:00).
  It was pretty straight-forward, easy enough no need to be bloated with "user-friendlyness" getting in the way.  As you pointed out... it did just one thing well.

**Comment by russel** [comment]
Bizarrely perhaps, having a separate executable, but based on some shared code, would probably be better than trying to integrate recording into the player. The counter-example is the use case of "record what I am watching now".

Unattended recording is quite complicated in many ways, yes there is the time, but things can get moved, especially series. The MPEG-TS stream carries programme information that can assist greatly in recording, but until the GStreamer_Rs MPEG-TS library is in place I am not sure I wan to go there: using the GStreamer_Sys FFI API is possible but really not desirable – it is intended as a base for the GStreamer_Rs binding.

**Comment by dougK44883** [comment]
> Unattended recording is quite complicated in many ways, yes there is the time, but things can get moved, especially series.

That's where the "manual" aspect came in.  From my perspective, you actually scheduled a "time" on a date/day to record whatever you named it.  I disabled the EPG thread, but supposedly you could have favorites and it would record things as they showed up.  Yes, I would check the TV schedule weekly and confirm what I wanted and what dropped off.

As for the rest of your comment, I have some idea of what those terms are about, with no real technical understanding.

**Comment by russel** [comment]
Sorry about the technical verbiage, the summary is I need to fix a program and a library to be able to do anything with EPGs, and I need to learn all about the program to do it.

For the moment it sounds like a second program (me-tv-record) that can be used with or without a GUI simply to record programmes to MPEG-4 files would meet the requirement. The hard bit will be the command line, GUI, and scheduling not the actual recording. Having said this, given the Me TV code only works on Linux, using the operating systems 'at' scheduling should make it straightforward.

**Comment by dougK44883** [comment]
Having put that out there, if I knew what I was doing, I think, somehow ffmpeg can 'capture' a dvb stream and extremely crude scheduling could be done with cron.d entries.  Yea, this would require almost as much intervention as the old vhs days.  :)  nevertheless I'm grateful you're even wondering about it.
  
Ultimately I purchased a commercial  device, tablo.  It's not ideal, requiring the internet to use it yet locally accessible via pc or streaming devices.  I [discovered](https://github.com/mjremijan/ferris-tablo/blob/master/create_mp4_from_tablo_directory.sh) a way to retrieve shows and limit some of their data mining.   (free OTA programing ...but you have to pay, even if indirectly, via internet access to view it - wtf)

**Comment by russel** [comment]
You stirred me into action yesterday. I found that the GStreamer pipeline:

    gst-launch-1.0 filesrc location=<path-to-ts-file> ! decodebin ! x264enc ! mp4mux ! filesink location=<path-to-mp4-fil>

creates an MPEG4 file from an MPEG-TS file. Armed with this knowledge I have started writing a command line program to do recording of a named channel from a given time for a given duration or to an end time. If it works I can consider doing a GUI, and eventually connecting to the EPG.

Once I have something that begins to look like it is working, I will create the GitHub repository for that code – I am keeping it separate from this repository, at least for now, on the thinking that having two distinct small things that work well is better than trying to munge it all into one thing. At least for now anyway.

**Comment by russel** [comment]
It seems we can record programs. Not from the Me TV GUI (at least not as yet), but with two executables that are command line prgrams. me-tv-record records a name channel from now for a duration. me-tv-schedule starts a recording using me-tv-record on a given channel from a start time for a duration (can be given as an end time). Scheduling uses the at system.

Currently recording happens on adapter 0 frontend 0 only, even though there are options to change this. It's a work in progress. :-)

**Comment by russel** [comment]
I think the answer to the question of this is now: it does. So I am going to close this issue as done, and open other issues to handle the known problems with the facility.

**Comment by dougK44883** [comment]
> You stirred me into action yesterday. I found that the GStreamer pipeline:

When you get stirred you really make things happen.  After I retired my old jessie pc I dismantled it so I could swap cases - someday, currently I don't have any turners in a functioning pc.  After the holiday business I need to get a system running and _build_(?) me-tv 3.x - it's a Christmas Miracle

**Comment by russel** [comment]
I use USB DVB-T2 devices plugged in to laptops. I have a dual tuner WinTV, a single tuner PC-TV. Also I have a couple of NooElec devices, but they are for SDR and DAB really. One person who reported in as using Me TV 3 some time back had a PCI bus dual tuner card so they are known to work as well.
