### ISSUE TITLE
full screen mode

### ISSUE THREAD

**Issue by tomidis** [Me-TV/Me-TV#11]
It would be nice to have an option to switch from window to full screen (and opposite) with mouse double click.
Can the title bar be entirely hidden in full screen mode? it can appear with mouse move.

**Comment by russel** [comment]
I will investigate the double click to switch modes.

In full screen mode, pressing the Escape key should revert to window mode. This perhaps needs documenting. Actually there needs to be some documentation, currently there is none.

The title bar hides for me on Debian Sid and Fedora Rawhide, with mouse move causing it to reappear. 

I wonder if this issue should be split in two to separate what are two different problems?

**Comment by tomidis** [comment]
Yes, it can be splitted in two issues

**Comment by russel** [comment]
Split into Issue #12 and #13
