### ISSUE TITLE
Show TV immediately

### ISSUE THREAD

**Issue by tomidis** [Me-TV/Me-TV#14]
Great to have this option, but for me it seems to not working correctly.
When checked "Show TV immediately if possible:", there are a few issues:
a - The application doesn't remember the option "Start with last channel.", so it always automatically switch back to "Start with the default channel:"
b - As a result of issue "a", if there is no inserted default channel, you get the message "The default channel is the empty string and cannot be tuned to."
c - with option "Start with the default channel:", it doesn't remember inserted channel if you don't press keyboard Enter (Preferences window doesn't have an OK button, or at least is not visible)
Until I find out that the keyboard Enter saves entered channel, I was thinking that application doesn't accept entered value because of the wrong format, so I tried with numbers, different signs in front of channel,...... so I found out, when you enter the wrong channel name, you get the message "The default channel could not be found for immediate TV display."
But the correct format is simply the channel name (from channels dropdown list)
In the end, it seems to be working only "Start with the default channel:"

**Comment by russel** [comment]
a. got fixed a few minutes ago with release 3.0.1.

b. is likely a one off issue to do with reading a configuration file that is not complete, it means the options revert to the default. This has a TODO in the code, but should perhaps have a separate issue.

c. is an interesting problem. ;-) I just put in a text entry box as a "quick hack". As you say it should really be set using the drop down list of possibilities. There are some issues doing this though. This problem should be separated out to it's own issue.

**Comment by tomidis** [comment]
I just downloaded and tested this new release 3.0.1
I can confirm the "a" issue fixed now.
Regarding "c", did you meant that there should be an channels dropdown list in the Preferences window?
Because I don't have it, and maybe if there exists one, then it will be much easier to select the default channel.

**Comment by russel** [comment]
Excellent, I am glad a is fixed. I suspect after the first use after a change in the configuration file format everything works as it should. This should work better, perhaps you might add an issue for it specifically?

Yes there should be a channels drop down list, but it isn't there yet (just a text entry box) – it is non-trivial to implement for lots of deep Rust reasons. I am working on this now. I hope to have it working by tomorrow or Tuesday. Progress so far is good.

**Comment by russel** [comment]
I believe release 3.0.2 deals with the channel choice in the preferences dialog, so I think all the issues raised here have been addressed.

If there are still problems or new ones, probably best to start a new issue for them.
