### ISSUE TITLE
Full screen mouse pointer not hidden

### ISSUE THREAD

**Issue by tomidis** [Me-TV/Me-TV#18]
Me-TV in full screen doesn't hide the mouse pointer

**Comment by russel** [comment]
Changeset https://github.com/Me-TV/Me-TV/commit/f991b5418d192fa1621e6cfdbd676385244b13c7 should fix this. However, I want to fix #19 before declaring a bug fix release. Also I get the feeling that things are not working entirely correctly when leaving fullscreen mode. :-(

**Comment by russel** [comment]
I am going to close this issue as fixed, and raise another issue for the unfullscreen behaviour problem if it persists.
