### ISSUE TITLE
me-tv-record fails to properly close file on ctrl-c

### ISSUE THREAD

**Issue by russel** [Me-TV/Me-TV#28]
If me-tv-record is run directly and terminated using ctrl-c the pipeline is not shut down correctly and the resulting file is not playable.

**Comment by russel** [comment]
This should be fixed by commit https://github.com/Me-TV/Me-TV/commit/177aee86f022507a8cbdeba1b7392781e795e53a

**Comment by dougK44883** [comment]
> If me-tv-record is run directly and terminated using ctrl-c the pipeline is not shut down correctly and the resulting file is not playable.

^C seems to have no effect?  Using system-monitor, stop process also leaves an un-playable file :(

**Comment by russel** [comment]
Both ctrl-C and sending SIGTERM should do a proper termination. I wonder if are using a me-tv-record version before I got it working correctly. Using SIGKILL via 'kill -9' or htop, top, system monitor will always result in a broken file since the process is terminated with severe prejudice and has no chance to tidy up.

I guess I am leading up to the age old adage "it works for me".

**Comment by dougK44883** [comment]
> I guess I am leading up to the age old adage "it works for me".

I will begrudgingly accept that, after all else.  
Presuming  this is not your answer for longer recordings as well.  :)
