### ISSUE TITLE
me-tv-record

### ISSUE THREAD

**Issue by dougK44883** [Me-TV/Me-TV#32]

**Comment by dougK44883** [comment]
Now for the part that brought me here in the first place... and I guess why I started "bothering" you.  me-tv-record.
 I added --verbose > logfile   still have this output

```
~/DVB$ me-tv-record --channel WTOL --duration 5 --output /media/dvr/show.mpeg --verbose >me-tv-record.log
thread '<unnamed>' panicked at 'cannot make a x264enc', libcore/option.rs:1008:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
fatal runtime error: failed to initiate panic, error 5
Aborted
```
So I added the RUST_BACKTRACE=1 copy/pasted into attached file.  All I get from that, it panicked and concluded it failed to initiate panic.  Do any of these message give you a clue?  

[me-tv-record.log.TXT](https://github.com/Me-TV/Me-TV/files/2716013/me-tv-record.log.TXT)
[me-tv-record.rust_backtrace.TXT](https://github.com/Me-TV/Me-TV/files/2716022/me-tv-record.rust_backtrace.TXT)

**Comment by dougK44883** [comment]
###  @russel  Are your going to believe this!?!?
ocd'd on the errors, found the error message in me-tv-record  line 169:               gstreamer::ElementFactory::make("x264enc", None).expect("cannot make a x264enc")
  Searched on ElementFactory:make then x264enc - finally discovered...  [x264enc](https://www.freedesktop.org/software/gstreamer-sdk/data/docs/latest/gst-plugins-ugly-plugins-0.10/gst-plugins-ugly-plugins-x264enc.html) is, as you probably knew, but have too many to sort through :), is part of the ugly gstreamer1.0-plugins. Found [Plugin Information](https://www.freedesktop.org/software/gstreamer-sdk/data/docs/latest/gst-plugins-ugly-plugins-0.10/gst-plugins-ugly-plugins-plugin-x264.html#plugin-x264)  Tried to stat [libgstx264.so](https://packages.debian.org/buster/amd64/gstreamer1.0-plugins-ugly/filelist) got `stat: cannot stat '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstx264.so': No such file or directory`  Well, that's when I actually noticed the **ugly** and thinking it's not in the list.  After installing [gstreamer1.0-plugins-ugly](https://packages.debian.org/buster/gstreamer1.0-plugins-ugly) and pulling a couple other dependencies - are you going to believe this!? 
`RUST_BACKTRACE=1 me-tv-record --channel WTOL --duration 5 --output /media/dvr/show.mpeg --verbose`  gave me a 5min **_error free_** video!!!

**Comment by russel** [comment]
I have amended the README to try and avoid this by listing gstreamer1.0-libva as a dependency that should be installed. Hopefully what is there now will be better for new people arriving at Me TV so they do not have the hassles you have had to suffer.

But, yay, recording is working in ATSC land as well as DVB-T land. :-)

If there are any changes to the README you think would help others do let me know and I'll make them.
