### ISSUE TITLE
closing channel window

### ISSUE THREAD

**Issue by dougK44883** [Me-TV/Me-TV#35]
Closing the channel window other than the [X] in the title bar (if you so have one somewhere) or tapping the frontendX/adaptorX button give an error box.  'Output widget was destroyed'  takes 3 ok taps to clear, and the frontendX/adaptorX button is left "on".
  I discovered this closing from a right-click in the panel.  I use mate-desktop (wonderful thing about linux, it's not one-size-fits-all, you find what works for you)  So I tried it from the title bar, which I guess is from the window manager, from mate-desktop.  Either one of these options create the _trivial annoyance_, just say'n

**Comment by russel** [comment]
I get it on GNOME Shell as well. How annoying.

And the "show channel" button remains on. Nasty.

**Comment by russel** [comment]
I believe this is now fixed. It is for me on GNOME Shell and so should be for other GTK+ window managers as well. 

Obviously if I am wrong, the issue should be reopened. :-)
