### ISSUE TITLE
v3.0.8 building error

### ISSUE THREAD

**Issue by tomidis** [Me-TV/Me-TV#36]
I cannot build this version.
When using:
``cargo install --root=$HOME/Built``
I get the following 3 errors:
``error[E0658]: scoped xxxx `clippy::approx_constant` is experimental (see issue #44690)
 --> /home/usr/.cargo/git/checkouts/sys-5eecc06807450db7/508d926/glib-sys/src/lib.rs:6:10``
``error[E0658]: scoped xxxx `clippy::type_complexity` is experimental (see issue #44690)
 --> /home/usr/.cargo/git/checkouts/sys-5eecc06807450db7/508d926/glib-sys/src/lib.rs:6:35``
``error[E0658]: scoped xxxx `clippy::unreadable_literal` is experimental (see issue #44690)
 --> /home/usr/.cargo/git/checkouts/sys-5eecc06807450db7/508d926/glib-sys/src/lib.rs:6:60``

Precompiled me-tv binary at bintray is 1,2 kB in size ?!?

**Comment by dougK44883** [comment]
> Precompiled me-tv binary at bintray is 1,2 kB in size ?!?

 I'm sure you've discovered this.  Turns out to be a text file... something got flubbed up.

**Comment by russel** [comment]
Authority problem Travis-CI → Bintray. I'll patch with a manual drop of executable I built for 3.0.8 and then try a 3.0.9 when Travis-CI tell me how to solve the problem.

**Comment by russel** [comment]
Uploaded but without GPG files.

**Comment by tomidis** [comment]
I cannot start this binary, nothing happens

**Comment by russel** [comment]
@tomidis I am guessing there must be a library or plugins version problem. The manual uploaded executables were compiled on Debian Sid, the ones from Travis-CI are compiled on Ununtu Xenial. Until Travis-CI and Bintray give me data on how to do the upload from Travis-CI, I am unsure what to do.

**Comment by dougK44883** [comment]
I have successfully downloaded `Me TV 3.0.8` and works as expected on my system.  AND I can close the viewer window by any method without issue. - ie, window list in panel or context menu in title bar.

**Comment by russel** [comment]
@tomidis I am not sure what happened with your:
```
cargo install --root=$HOME/Built
```
I tried:
```
cargo install --root=/tmp/Me_TV
```
and it all seemed to work fine. However I am using Rust stable, are you using Rust nightly?

**Comment by tomidis** [comment]
I didn't change or update Rust since last Me-TV compile (v3.0.6)
``rustc 1.29.1 (b801ae664 2018-09-20)``
I'm guessing it's stable?
However, since last compile, I updated Mint from 19 to 19.1

**Comment by tomidis** [comment]
OK, now I tried again to compile the v3.0.6 and it's successful
... and now I tried to compile v3.0.7 and I'm getting the same 3 errors [E0658]

**Comment by tomidis** [comment]
I think this issue can be closed.
Now I updated Rust to version:
`stable installed - rustc 1.32.0 (9fda7c223 2019-01-16)`
then again compiled v3.0.8 and it's successful

I'm not getting back to Windows, but in Linux it's really frustrating all these dependencies.... will the application work or not depends from snowing in Arctic, solar winds, an ISS astronauts coughing, ants farting,.....
I can understand all people who gave up from Linux

**Comment by dougK44883** [comment]
>  I can understand all people who gave up from Linux

To be fair, this isn't the same as installing from your distribution's package manager/repository.  

Building a package from it's source is "developer level" work more-or-less.  Routine users generally don't make and build first... hang in there.    

I believe Linux Mint is one of the user friendly-est distribution available.I had started using Mint between Cassandra and Gloria, found it "that much nicer" than ubuntu.  (then the user friendly stuff got in my way and just want straight up debian)

**Comment by tomidis** [comment]
I agree, maybe it's not fair to compare "developer" with "user" level of work, but anyway I think that Linux is a far more demanding for "end user" than Windows. In Linux the end user very often must at least a little scratch into the "developer level".
I tried again to use the v3.0.8 from Bintray, and I cannot start it.
Also, after returning the binary compiled by myself, now I have some problem with GStreamer.
Now after starting of mine binary, I get the following two messages:
`There was an error reported on the GStreamer bus......`
and
`Could not set play state, perhaps the aerial isn't connected? Try running with GST_DEBUG=3 me-tv`
So when I run "GST_DEBUG=3 me-tv", I get:
``thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', src/libcore/result.rs:1009:5``
``note: Run with `RUST_BACKTRACE=1` for a backtrace.``
``thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 1', /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/slice/mod.rs:2463:10``
``(me-tv:1742): GLib-GObject-CRITICAL **: 15:50:36.459: g_object_get: assertion 'G_IS_OBJECT (object)' failed``
``Segmentation fault (core dumped)``

**Comment by russel** [comment]
@tomidis I think the issue is not so much Windows vs Linux per se, more "polished product provided on Windows" vs "work in progress on Linux" – though I'd agree Windows and macOS tend to be end user electronics whereas Linux is a computing platform.

That failure at the end there is really weird. The problem is clearly one I have not set up a proper error handling for – work in progress vs polished product thing – it looks like you are not in the group that the /dev/dvb files get created as group video. This means the user needs to be in group video in order to use the device. I am not at all sure where the index out of bounds comes from. Again though it looks like a error handling where I have not done the polished end user thing, just the developer quick hack thing.

The segmentation fault is truly weird. Given the previous errors that should not have happened. :-(

**Comment by tomidis** [comment]
Now I compiled again v3.0.6 and getting the same 2 error messages, but I forgot to switch ON the room antenna amplifier. So I tested this behavior, and every time I switch OFF amplifier, when starting Me-TV I get these messages, and when the amplifier is ON, the Me-TV starts normally without error.
This applies to all versions, but only the ones compiled by myself. In conclusion, the Me-TV starts with these two errors only with low level DVB-T signal, but with enough signal level, it starts normally without errors.

I tried one more time binary from Bintray, and it won't start

**Comment by dougK44883** [comment]
just as a confirmation...

```
~$ GST_DEBUG=3 me-tv --version
Me TV 3.0.8
~$ GST_DEBUG=3 me-tv
0:00:08.687582279  5740 0x55e6fe82b580 WARN              dvbbasebin parsechannels.c:394:parse_and_configure_from_v5_conf_file:<source> Failed to map property 'VCHANNEL'
0:00:08.687657688  5740 0x55e6fe82b580 WARN              dvbbasebin parsechannels.c:394:parse_and_configure_from_v5_conf_file:<source> Failed to map property 'VIDEO_PID'
0:00:08.687684333  5740 0x55e6fe82b580 WARN              dvbbasebin parsechannels.c:394:parse_and_configure_from_v5_conf_file:<source> Failed to map property 'AUDIO_PID'
0:00:08.983813653  5740 0x55e6fe82b580 FIXME                 dvbsrc gstdvbsrc.c:2097:gst_dvbsrc_is_valid_trans_mode: No transmission-mode sanity checks implemented for this delivery system
0:00:08.983861148  5740 0x55e6fe82b580 FIXME                 dvbsrc gstdvbsrc.c:2161:gst_dvbsrc_is_valid_bandwidth: No bandwidth sanity checks implemented for this delivery system
0:00:09.114974927  5740 0x55e6fe82b580 WARN                  dvbsrc gstdvbsrc.c:2226:gst_dvbsrc_output_frontend_stats:<dvbsrc0> There were errors getting frontend status information: 'Invalid argument'
0:00:09.480337452  5740 0x55e6fefbf140 FIXME                default gstutils.c:3981:gst_pad_create_stream_id_internal:<dvbsrc0:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:00:16.708200883  5740 0x55e6fefbf050 WARN        mpegtspacketizer mpegtspacketizer.c:2331:mpegts_packetizer_pts_to_ts: Not enough information to calculate proper timestamp
```
It plays a station.  The warning messages are apparently arbitrary, they aren't new.  I'm running debian buster/testing with all the necessary gstreamer dependencies.

**Comment by russel** [comment]
Someone else has just reported this "Permission Denied" problem. It is very strange. It must be related to a change I made recently in that code, but all I did was a bit of "cut and paste" reintegration to make things simpler – supposedly. What was seemed to be OK what is seems not to be, and yet the code running should be the same.

Could someone run with RUST_BACKTRACE=1 so that the line number in frontend_manager.rs of the problem is known.  Thanks.

**Comment by russel** [comment]
The change noted above should stop the "permissions error" terminating the program. It should just stop the watching of insert and remove of adapters. However this is a temporary thing, I need to find out why this has just started happening, and fix it properly.

**Comment by russel** [comment]
@dougK44883 I haven't had any feedback regarding those FIXME issues in gstdvbsrc and gstutils. I suspect I will have to investigate the former myself, and just leave the latter as "someone else's problem".

As for the WARN in dvbbasebin, I will have to push a bit harder.

**Comment by russel** [comment]
@tomidis Sorry my uploads aren't working for you. I am not sure what the problem is. :-( Hopefully the Travis-CI people can sort out the permissions problem (they are on the job) and we can get to a 3.0.9 release using that workflow.

**Comment by tomidis** [comment]
This issue was related to old Rust version, so I think it can be closed.
