### ISSUE TITLE
Me-TV 3.0.9 crashes on startup

### ISSUE THREAD

**Issue by opqld** [Me-TV/Me-TV#37]
This machine is running Arch updated to the most recent package versions, with Rust 1.32.
Me-TV is cloned from this git repo. 
Compiled with the 'debug' flag produces the following output when launched with RUST_BACKTRACE=full:

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', src/libcore/result.rs:1009:5
stack backtrace:
   0:     0x5644a4dd3133 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::he84da11a41e773ce
   1:     0x5644a4dcd778 - std::sys_common::backtrace::_print::hf6a48c4afe230abd
   2:     0x5644a4dd20a4 - std::panicking::default_hook::{{closure}}::h9a96b678afdbc21a
   3:     0x5644a4dd1e0d - std::panicking::default_hook::hbcde5d495b1bd60b
   4:     0x5644a4dd27b0 - std::panicking::rust_panic_with_hook::hdf7497777e017561
   5:     0x5644a4dd2331 - std::panicking::continue_panic_fmt::h063725f0fd36e660
   6:     0x5644a4dd2215 - rust_begin_unwind
   7:     0x5644a4de9a7c - core::panicking::panic_fmt::h95aacf5fdbb0a687
   8:     0x5644a47bc10d - core::result::unwrap_failed::h478cef6f11f5fbf9
                               at /build/rust/src/rustc-1.32.0-src/src/libcore/macros.rs:26
   9:     0x5644a47b7eaa - <core::result::Result<T, E>>::unwrap::h83497b8816838043
                               at /build/rust/src/rustc-1.32.0-src/src/libcore/result.rs:808
  10:     0x5644a4792181 - me_tv::frontend_manager::run::hf840829fa1329417
                               at src/frontend_manager.rs:141
  11:     0x5644a4801f84 - me_tv::main::{{closure}}::{{closure}}::h39d101ce9418683b
                               at src/main.rs:125
  12:     0x5644a47a8dc7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h628fa136a9867bd1
                               at /build/rust/src/rustc-1.32.0-src/src/libstd/sys_common/backtrace.rs:136
  13:     0x5644a47d2b54 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h9cfdc76a5abfecd2
                               at /build/rust/src/rustc-1.32.0-src/src/libstd/thread/mod.rs:477
  14:     0x5644a48378d7 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hb6481e18d6d0064d
                               at /build/rust/src/rustc-1.32.0-src/src/libstd/panic.rs:319
  15:     0x5644a482abdf - std::panicking::try::do_call::h6297e9a6286c2074
                               at /build/rust/src/rustc-1.32.0-src/src/libstd/panicking.rs:310
  16:     0x5644a4de2f19 - __rust_maybe_catch_panic
  17:     0x5644a482a84f - std::panicking::try::had3f7868b0dedd93
                               at /build/rust/src/rustc-1.32.0-src/src/libstd/panicking.rs:289
  18:     0x5644a4837907 - std::panic::catch_unwind::h3a18bcae26882eb9
                               at /build/rust/src/rustc-1.32.0-src/src/libstd/panic.rs:398
  19:     0x5644a47d1fb3 - std::thread::Builder::spawn_unchecked::{{closure}}::h289912dadb6b56c5
                               at /build/rust/src/rustc-1.32.0-src/src/libstd/thread/mod.rs:476
  20:     0x5644a47d2f0f - <F as alloc::boxed::FnBox<A>>::call_box::hd092d31737c701b4
                               at /build/rust/src/rustc-1.32.0-src/src/liballoc/boxed.rs:673
  21:     0x5644a4dd9ffd - std::sys::unix::thread::Thread::new::thread_start::h075b38fc29fe00c4
  22:     0x7f2bccf5da9c - start_thread
  23:     0x7f2bcce73b22 - clone
  24:                0x0 - <unknown>

The interface starts but crashes when clicking the 'adaptor0/frontend0' button:

(me-tv:19161): Gtk-WARNING **: 17:11:25.874: Calling org.xfce.Session.Manager.Inhibit failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "Inhibit" with signature "susu" on interface "org.xfce.Session.Manager" doesn't exist

Warning: could not set inhibitor.
failed to create drawable
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
me-tv: xcb_io.c:263: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted

The 'could not set inhibitor' issue is related to XFCE (the default desktop) and has never been a problem before, although if anyone knows how to fix it, it would not hurt.

Me-TV has worked for the past year or so, since Russel first released it, but now even the old versions fail.

**Comment by russel** [comment]
The location of the problem appears to be related to the new code to handle remote controls. However, the final error report seems not to relate to the location of the problem! Weird.

That older Me TV versions no longer work is also weird.

I have made one trivial change, that should affect nothing, but does seem right for consistency anyway.

This is going to be a tricky one I fear.

**Comment by russel** [comment]
Ah. The change I made to my code has meant I think that the line numbers above and the line numbers I have are going to be different. This means I am not sure my hypothesis is even close. Can I get you to run again with the very latest from the Git repository? Sorry about this @opqld I should have thought about this point a few minutes ago.

**Comment by opqld** [comment]
Here's the updated output:

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', src/libcore/result.rs:1009:5
stack backtrace:
   0:     0x561a0a20c133 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::he84da11a41e773ce
   1:     0x561a0a206778 - std::sys_common::backtrace::_print::hf6a48c4afe230abd
   2:     0x561a0a20b0a4 - std::panicking::default_hook::{{closure}}::h9a96b678afdbc21a
   3:     0x561a0a20ae0d - std::panicking::default_hook::hbcde5d495b1bd60b
   4:     0x561a0a20b7b0 - std::panicking::rust_panic_with_hook::hdf7497777e017561
   5:     0x561a0a20b331 - std::panicking::continue_panic_fmt::h063725f0fd36e660
   6:     0x561a0a20b215 - rust_begin_unwind
   7:     0x561a0a222a7c - core::panicking::panic_fmt::h95aacf5fdbb0a687
   8:     0x561a09bf510d - core::result::unwrap_failed::h478cef6f11f5fbf9
                               at /build/rust/src/rustc-1.32.0-src/src/libcore/macros.rs:26
   9:     0x561a09bf0eaa - <core::result::Result<T, E>>::unwrap::h83497b8816838043
                               at /build/rust/src/rustc-1.32.0-src/src/libcore/result.rs:808
  10:     0x561a09bcb181 - me_tv::frontend_manager::run::hf840829fa1329417
                               at src/frontend_manager.rs:145
  11:     0x561a09c3af84 - me_tv::main::{{closure}}::{{closure}}::h39d101ce9418683b
                               at src/main.rs:125
  12:     0x561a09be1dc7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h628fa136a9867bd1
                               at /build/rust/src/rustc-1.32.0-src/src/libstd/sys_common/backtrace.rs:136
  13:     0x561a09c0bb54 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h9cfdc76a5abfecd2
                               at /build/rust/src/rustc-1.32.0-src/src/libstd/thread/mod.rs:477
  14:     0x561a09c708d7 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hb6481e18d6d0064d
                               at /build/rust/src/rustc-1.32.0-src/src/libstd/panic.rs:319
  15:     0x561a09c63bdf - std::panicking::try::do_call::h6297e9a6286c2074
                               at /build/rust/src/rustc-1.32.0-src/src/libstd/panicking.rs:310
  16:     0x561a0a21bf19 - __rust_maybe_catch_panic
  17:     0x561a09c6384f - std::panicking::try::had3f7868b0dedd93
                               at /build/rust/src/rustc-1.32.0-src/src/libstd/panicking.rs:289
  18:     0x561a09c70907 - std::panic::catch_unwind::h3a18bcae26882eb9
                               at /build/rust/src/rustc-1.32.0-src/src/libstd/panic.rs:398
  19:     0x561a09c0afb3 - std::thread::Builder::spawn_unchecked::{{closure}}::h289912dadb6b56c5
                               at /build/rust/src/rustc-1.32.0-src/src/libstd/thread/mod.rs:476
  20:     0x561a09c0bf0f - <F as alloc::boxed::FnBox<A>>::call_box::hd092d31737c701b4
                               at /build/rust/src/rustc-1.32.0-src/src/liballoc/boxed.rs:673
  21:     0x561a0a212ffd - std::sys::unix::thread::Thread::new::thread_start::h075b38fc29fe00c4
  22:     0x7f20841bba9c - start_thread
  23:     0x7f20840d1b22 - clone
  24:                0x0 - <unknown>

Then once the program crashes, there is a different output after the XFCE-related inhibitor message:

Xlib: sequence lost (0x10000 > 0x20fe) in reply type 0x0!
free(): invalid pointer
Aborted

**Comment by russel** [comment]
Thanks for redoing. The error now matches a place where the error can happen. :-) On the other hand this bit of code used to work for you and others, and is now not working as it should. The simple move of code alone should not have caused this change of behaviour but something has. There is though now a handle on progressing things constructively. I suspect though I will to have to rely on others to do testing as I am not seeing the problem here locally. I suspect I may have an inkling though of something… I shall go play.

**Comment by russel** [comment]
The change noted above should stop the "permissions error"  terminating the program. It should just stop the watching of insert and  remove of adapters. However this is a temporary thing, I need to find  out why this has just started happening, and fix it properly.

**Comment by opqld** [comment]
Just as you said - the initial output is now as follows, and the crash remains the same.

Watch on /dev/ failed: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
Frontend Manager terminated.

[xcb] Too much data requested from _XRead
[xcb] This is most likely caused by a broken X extension library
[xcb] Aborting, sorry about that.
me-tv: xcb_io.c:742: _XRead: Assertion `!xcb_xlib_too_much_data_requested' failed.
Aborted

Thanks for all the work you've put into this.

**Comment by russel** [comment]
It is good that the PermissionDenied is now just terminating the frontend manager rather than the whole program. However, it is annoying that this didn't used to happen for you, and the code hasn't actually changed, but this now it is happening. I think I have an inkling why, but if true, it is really, really annoying. But workableroundable.

As for the [xcb] _XRead problem, I am at a total loss. I have been using Xwayland now for a while rather than Xorg, I'll try with Xorg and see I can get the same behaviour using Debian Sid.

**Comment by russel** [comment]
I now do not understand why the PermissionsDenied is happening for you. :-( Here on a Debian Sid machine logged in as my wife (so no special permissions, unlike my account) it all works fine. On the other hand I have found some other bugs that are permission related that it seems you have not seen. :-(

**Comment by russel** [comment]
Regarding the [xcb] problem, there is a hint out in the Webby-verse that this might be an OpenGL issue. To test this, me-tv can be started such that it will not try and do OpenGL at all:
```
me-tv --no-gl …
```
Might be worth a try.

**Comment by dougK44883** [comment]
I don't know anything...  and it varies amongst systems, and why would it change.
My frontendX are in the group video as well as myself
```
ls -alr /dev/dvb/adapter*
crw-rw----+ 1 root video 212, 4 Jan  9 17:24 frontend0
crw-rw----+ 1 root video 212, 4 Jan  9 17:24 frontend0
~$ id
groups=1000(dj),4(adm),27(sudo),29(audio),30(dip),44(video),46(plugdev),107(netdev)
```  [edited]

**Comment by russel** [comment]
@dougK44883  udev does the group assignment and I think it is video for all frontends. However the remote controls appear to get group input. So users of DVB adapters with remote controls also need to be in group input as well as audio and video for things to fully work.

**Comment by opqld** [comment]
This may give you some clues, Russel as to the possible culprit.

Running the executable with the --no-gl switch has stopped the crashing; both in the freshly compiled debug version and old version 3.0.0 that I have kept for testing.

It now starts and runs, but in full-screen mode the computer fan soon starts to work overtime, so something is eating a few resources in the background.

The start-up message remains unchanged:

Watch on /dev/ failed: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
Frontend Manager terminated.

Where the mystery has gone deeper is that after it started successfully once, it now seems to work even without the above gl-related switch, although it still makes the machine work for it.

Nothing of note has been updated on this machine over the last couple of days.

Cheers.

**Comment by tomidis** [comment]
I just compiled this version, and for me it works normally

**Comment by russel** [comment]
@opqld So there does seem to have been an OpenGL connection to the problem, but it seems ephemeral, which is a real annoyance as it is hard to even try and chase those.

Full screen mode is always going to be a bit stressful I suspect since currently the GStreamer pipeline always goes for best quality. I need to come up with a way of allowing people to set lower quality requirements to ameliorate this. No solid ideas just yet though.

Not being able to watch on /dev/ is really weird. I currently have no ideas on this as my hypothesis failed to be confirmed by local experimentation.

**Comment by opqld** [comment]
A quick update:
The latest 'release' version continues to work, although still with the same permission-related issue on startup as referenced above.
Another machine with OpenSUSE Tumbleweed does not generate that output.
So as Russel says, it's an ephemeral issue and may well solve itself after a few of the regular Arch rolling package updates.
So I guess we can close this one for the time being at least.
