### ISSUE TITLE
Default "adaptor" setting

### ISSUE THREAD

**Issue by tomidis** [Me-TV/Me-TV#6]
It would be nice to have the default "adaptor" setting.
So when you start the app, it goes straight to the TV.
Also, the setting for start with the last viewed channel (this can also be hardcoded)

**Comment by russel** [comment]
It strikes me that these perhaps ought to be user options with a default setting. The different people can have different default behaviours.

**Comment by tomidis** [comment]
> user options with a default setting

Yes, that's what I thought also, maybe I didn't wrote it clearly enough

**Comment by russel** [comment]
What you write worked for me, I was just rewriting the idea so as to reinforce the idea explicitly. I shall set about putting this in shortly.

**Comment by russel** [comment]
Changeset https://github.com/Me-TV/Me-TV/commit/a1a00866e797ad5a2a9a2b6c86f75c6919231239 should provide at the the first draft of this feature.

Currently only adapter 0, frontend 0 is allowed to start showing the default channel.

**Comment by russel** [comment]
I will now add storing the last channel for each adapter/frontend and the option to choose default channel or last channel, but I am thinking only to start the adapter 0, frontend 0, i.e. only ever start one channel automatically.

**Comment by russel** [comment]
I believe changeset https://github.com/Me-TV/Me-TV/commit/f7373dc6dbd1bbac00b6002cbc96936a659c3b75 adds the rest of the functionality of this issue. I am certain there are bugs in the code, but I propose creating new issues for them rather than keep this issue going.

**Comment by russel** [comment]
There were some errors and some missing code. All now present. v3.0.1 should do what I think was the goal of this issue.
